# frozen_string_literal: true

source "https://rubygems.org"

gem 'sinatra'
gem 'rspec'
gem 'capybara'
gem 'simplecov', require: false, group: :test

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
